#!/bin/bash
#install updates
yum update -y
#intall apache/php/mysql
yum install -y httpd24 php56 mysql55-server php56-mysqlnd
#start apache
service httpd start
#set apache to start on restart
chkconfig httpd on
#write php info file  
echo "<?php phpinfo(); ?>" > /var/www/html/phpinfo.php
#copy from s3 to instance
aws s3 cp s3://mybbhtml /var/www/html
